# Generated by Django 4.2.2 on 2023-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_googleanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nome do Script')),
                ('script', models.TextField(help_text='Adicione o script completo, inclusive com as tags <script></script>.', verbose_name='Script')),
                ('place', models.CharField(choices=[('HD', 'Head/Cabeçalho'), ('FT', 'Footer/Rodapé')], help_text='Escolha onde o script deve ser inserido.', max_length=2, verbose_name='Local')),
                ('is_active', models.BooleanField(default=True, help_text='Os scripts inativos deixarão de ser inseridos nas páginas.', verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
    ]
