# Generated by Django 5.1.2 on 2024-11-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='force_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
