# Generated by Django 4.2.2 on 2023-08-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postagemforumimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
