# Generated by Django 4.2.2 on 2023-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocos',
            options={'ordering': ['id'], 'verbose_name': '3 - Blocos', 'verbose_name_plural': '3 - Blocos'},
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_3',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_4',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
    ]
