# Generated by Django 5.1.2 on 2024-11-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postagemforumimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
